[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.9.0",
    "fastapi>=0.121.1",
    "fastmcp>=2.13.0.2",
    "httpx>=0.28.1",
    "pyright>=1.1.407",
]
